spring:
  datasource:
    url: jdbc:postgresql://45.132.107.16:5432/aziano
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.default_schema: aziano