spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:postgresql://45.132.107.16:5432/aziano
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.default_schema: aziano
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true
    schemas: aziano
  thymeleaf:
    cache: false

mapstruct:
  defaultComponentModel: spring  # Установить Spring как компонентную модель для MapStruct

lombok:
  addLombokGeneratedAnnotation: true  # Добавить аннотацию @Generated для методов Lombok

server:
  servlet:
    session:
      timeout: 12h # This sets the timeout to 12 hours