spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/aziano
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true
    schemas: public